openapi: 3.0.0
info:
  title: Agents API
  description: API for managing agents with CRUD operations
  version: 1.0.0
servers:
  - url: 138.197.71.145:3000
    description: API Server

paths:
  /agents:
    get:
      summary: Get all agents
      description: Retrieves a list of all agents, converting UPPER_CASE fields to camelCase.
      responses:
        "200":
          description: Successfully retrieved the list of agents.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Agent"
        "500":
          description: Internal Server Error

    post:
      summary: Create a new agent
      description: Adds a new agent to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Agent"
      responses:
        "201":
          description: Agent created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Agent"
        "400":
          description: Bad request (e.g., agent already exists)
        "500":
          description: Internal Server Error

  /agents/{agentCode}:
    get:
      summary: Get an agent by agentCode
      description: Retrieves a single agent by their agentCode.
      parameters:
        - name: agentCode
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully retrieved the agent.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Agent"
        "404":
          description: Agent not found
        "500":
          description: Internal Server Error

    patch:
      summary: Partially update an agent
      description: Updates specific fields of an agent without affecting others.
      parameters:
        - name: agentCode
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Agent"
      responses:
        "200":
          description: Agent updated successfully.
        "400":
          description: No fields to update.
        "404":
          description: Agent not found.
        "500":
          description: Internal Server Error.

    delete:
      summary: Delete an agent
      description: Deletes an agent by agentCode.
      parameters:
        - name: agentCode
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Agent deleted successfully.
        "404":
          description: Agent not found.
        "500":
          description: Internal Server Error.

components:
  schemas:
    Agent:
      type: object
      properties:
        agentCode:
          type: string
          example: "A007"
        agentName:
          type: string
          example: "John"
        workingArea:
          type: string
          example: "Data"
        commission:
          type: string
          example: "0.01"
        phoneNumber:
          type: string
          example: "077-25814763"
        country:
          type: string
          example: ""

